version: '3.8'

services:
  # Web application service
  web:
    build: .
    container_name: recruiter_app_web
    restart: always
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - DB_TYPE=postgresql
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=recruiter_app
      - SECRET_KEY=change-this-in-production
      - BABEL_DEFAULT_LOCALE=en
      - BABEL_TRANSLATION_DIRECTORIES=translations
    volumes:
      - ./logs:/app/logs
    networks:
      - recruiter_network

  # PostgreSQL database service
  db:
    image: postgres:14
    container_name: recruiter_app_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=recruiter_app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - recruiter_network

  # Nginx service for production deployment
  nginx:
    image: nginx:latest
    container_name: recruiter_app_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/app/frontend
    depends_on:
      - web
    networks:
      - recruiter_network

volumes:
  postgres_data:

networks:
  recruiter_network:
    driver: bridge
